#!/usr/bin/env python
from waflib.extras import autowaf as autowaf
import os

# Mandatory variables
top = '.'
out = 'build'

controlcp_sources = [
    'basic_ui.cc',
    'control_protocol.cc',
    ]

def options(opt):
    autowaf.set_options(opt)

def configure(conf):
    autowaf.configure(conf)

def build(bld):
    obj              = bld.shlib(features = 'c cxx cshlib cxxshlib', source=controlcp_sources)
    # defines for this library
    obj.defines      = [ 'LIBCONTROLCP_DLL_EXPORTS' ]

    obj.export_includes = ['.', './control_protocol' ]
    obj.defines    +=  [ 'PACKAGE="ardour_cp"' ]
    obj.includes     = ['.', './control_protocol']
    obj.name         = 'ARDOUR_CP'
    obj.target       = 'ardourcp'
    obj.use          = 'ARDOUR'
    obj.install_path = bld.env['LIBDIR']

def shutdown():
    autowaf.shutdown()
