echo "Program Options"
echo " "
echo "COMMON_OPTIONS      : $COMMON_OPTIONS"
echo "PATH_OPTIONS        : $PATH_OPTIONS"
echo "TEST_OPTIONS        : $TEST_OPTIONS"
echo "BACKEND_OPTIONS     : $BACKEND_OPTIONS"
echo " "
echo "Build Environment Settings...."
echo " "
echo "HOST                : $HOST"
echo "MINGW_ROOT          : $MINGW_ROOT"
echo "PKG_CONFIG_PREFIX   : $PKG_CONFIG_PREFIX"
echo "PKG_CONFIG_LIBDIR   : $PKG_CONFIG_LIBDIR"
echo "PKGCONFIG           : $PKGCONFIG"
echo "AR                  : $AR" 
echo "RANLIB              : $RANLIB"
echo "CC                  : $CC"
echo "CPP                 : $CPP"
echo "CXX                 : $CXX"
echo "AS                  : $AS"
echo "LINK_CC             : $LINK_CC"
echo "LINK_CXX            : $LINK_CXX"
echo "WINRC               : $WINRC"
echo "STRIP               : $STRIP"
echo "PYTHON              : $PYTHON"
echo " "
echo "Path Environment Settings...."
echo " "
echo "BASE                : $BASE"
echo "BUILD_DIR           : $BUILD_DIR"
echo "BUILD_CACHE_FILE    : $BUILD_CACHE_FILE"
echo "TOOLS_DIR           : $TOOLS_DIR"
echo "PACKAGE_DIR         : $PACKAGE_DIR"
echo " "
echo "Config Environment Settings...."
echo " "
echo "APPNAME             : $APPNAME" 
echo "VERSION             : $VERSION" 
echo "DEBUG               : $DEBUG" 
echo "WITH_TESTS          : $WITH_TESTS"
echo "ARDOUR_DATA_DIR     : $ARDOUR_DATA_DIR"
echo " "
