#!/usr/bin/env python
from waflib.extras import autowaf as autowaf
import os

# Mandatory variables
top = '.'
out = 'build'

def options(opt):
    autowaf.set_options(opt)

def configure(conf):
    autowaf.configure(conf)

def build(bld):
    obj = bld(features = 'cxx cxxshlib')
    obj.source = '''
            wiimote.cc
            interface.cc
    '''
    obj.export_includes = ['./wiimote']
    obj.defines      = [ 'PACKAGE="ardour_wiimote"' ]
    obj.defines     += [ 'ARDOURSURFACE_DLL_EXPORTS' ]
    obj.includes     = ['.', '../libs']
    obj.name         = 'ARDOUR_WIIMOTE'
    obj.target       = 'ardour_wiimote'
    obj.uselib       = 'CWIID'
    obj.use          = 'ARDOUR_CP GTKMM2EXT'
    obj.install_path = os.path.join(bld.env['LIBDIR'], 'surfaces')

def shutdown():
    autowaf.shutdown()
