#!/usr/bin/env python
from waflib.extras import autowaf as autowaf
import os
import sys
import re

I18N_PACKAGE = 'alsa-backend'

# Mandatory variables
top = '.'
out = 'build'

def options(opt):
    autowaf.set_options(opt)

def configure(conf):
    autowaf.configure(conf)
    if conf.is_defined('USE_EXTERNAL_LIBS'):
        autowaf.check_pkg(conf, 'zita-resampler', uselib_store='ZITA_RESAMPLER',
                          atleast_version='1.6.0')

def build(bld):
    obj = bld(features = 'cxx cxxshlib')
    obj.source = [
            'alsa_audiobackend.cc',
            'alsa_midi.cc',
            'alsa_rawmidi.cc',
            'alsa_sequencer.cc',
            'alsa_slave.cc',
            'zita-alsa-pcmi.cc',
            ]
    obj.includes = ['.']
    obj.name     = 'ALSA_AUDIOBACKEND'
    obj.target   = 'alsa_audiobackend'
    obj.use      = 'ARDOUR ARDOUR_ALSA_UTIL ZITA_RESAMPLER'
    obj.uselib   = 'ALSA'
    obj.install_path  = os.path.join(bld.env['LIBDIR'], 'backends')
    obj.defines = ['PACKAGE="' + I18N_PACKAGE + '"',
                   'ARDOURBACKEND_DLL_EXPORTS'
                  ]
