#!/usr/bin/env python
from waflib.extras import autowaf as autowaf
from waflib import Options
import os
import sys

# Version of this package (even if built as a child)
MAJOR = '2'
MINOR = '1'
MICRO = '1'
LIBMIDIPP_VERSION = "%s.%s.%s" % (MAJOR, MINOR, MICRO)

# Library version (UNIX style major, minor, micro)
# major increment <=> incompatible changes
# minor increment <=> compatible changes (additions)
# micro increment <=> no interface changes
LIBMIDIPP_LIB_VERSION = '4.1.0'

# Variables for 'waf dist'
APPNAME = 'libmidipp'
VERSION = LIBMIDIPP_VERSION

# Mandatory variables
top = '.'
out = 'build'

path_prefix = 'libs/midi++2/'


libmidi_sources = [
        'midi.cc',
        'channel.cc',
        'ipmidi_port.cc',
        'parser.cc',
        'port.cc',
        'midnam_patch.cc',
        'mmc.cc',
        'mtc.cc',
]

libmidi_amalgamated_sources = 'midipp.cc'

def options(opt):
    autowaf.set_options(opt)
    opt.add_option('--test', action='store_true', default=False, dest='build_tests',
                    help="Build unit tests")

def configure(conf):
    conf.load('compiler_cxx')
    autowaf.configure(conf)

    if Options.options.build_tests:
        autowaf.check_pkg(conf, 'cppunit', uselib_store='CPPUNIT', atleast_version='1.12.0')


def build(bld):
    sources = libmidi_sources

    if bld.env['AMALGAMATE']:
        sources = libmidi_amalgamated_sources

    # Library
    obj              = bld.shlib(features = 'cxx cxxshlib', source=sources)
    obj.defines      = [ 'LIBMIDIPP_DLL_EXPORTS=1' ]

    # everybody loves JACK
    obj.export_includes = ['.']
    obj.includes     = ['.', '../surfaces/control_protocol', '../ardour' ]
    obj.name         = 'MIDIPP'
    obj.target       = 'midipp'
    obj.uselib       = 'OSX'
    obj.use          = 'EVORAL'
    obj.vnum         = LIBMIDIPP_LIB_VERSION
    obj.install_path = bld.env['LIBDIR']

    if bld.env['BUILD_TESTS'] and bld.is_defined('HAVE_CPPUNIT'):
        # Unit tests
        obj              = bld(features = 'cxx cxxprogram')
        obj.source       = '''
                test/MidnamTest.cpp
                test/testrunner.cpp
        '''
        obj.includes     = ['.', './src']
        obj.use          = 'MIDIPP'
        obj.uselib       = 'CPPUNIT'
        obj.target       = 'run-tests'
        obj.name         = 'MIDIPP_TESTS'
        obj.install_path = ''

def shutdown():
    autowaf.shutdown()
